FROM python:3.13.13-slim-trixie

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

#RUN apt-get update \
#    && apt-get install -y --no-install-recommends build-essential python3-dev bluez dbus python3-pip libglib2.0-dev \
#    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential python3-pip libglib2.0-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY config.json ./config.json

EXPOSE 8000

#HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=3)"

CMD ["python", "src/thexporter.py"]
# CMD ["python", "src/test1.py"]
