services:
  temp-humidity-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temp-humidity-exporter
    restart: unless-stopped
    network_mode: host
    #network_mode: bridge
    #ports:
    #  - "8000:8000"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      PYTHONUNBUFFERED: 1
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/run/dbus/system_bus_socket
    volumes:
      - ./config.json:/app/config.json:ro
      - /etc/bluetooth/main.conf:/etc/bluetooth/main.conf:ro
      - /run/dbus:/run/dbus:ro
